### ISSUE TITLE
Serialization/deserialization of Classes is broken with syck

### ISSUE THREAD

**Issue by carlallen** [collectiveidea/delayed_job#1051]
#996 broke serialization/deserialization of class objects with syck

`yaml_tag` uses psychs `yaml_tag` which syck ignores. This means it never actually adds the tags. syck defines `yaml_as` for it's own uses, it never defines or uses `yaml_tag`.

```
#delayed job 4.1.3

class TestClass
  def self.print_hello
    puts "hello"
  end
end

YAML::load(TestClass.to_yaml) # returns TestClass

YAML::load(TestClass.to_yaml).print_hello # prints "hello"
```

```
# with delayed_job 4.1.4

class TestClass
  def self.print_hello
    puts "hello"
  end
end

YAML::load(TestClass.to_yaml) # returns a instance of Class

YAML::load(TestClass.to_yaml).print_hello # NoMethodError: undefined method `print_hello' ...
```

**Comment by nruth** [comment]
What are the practical implications of this? I'm here via https://github.com/collectiveidea/delayed_job/pull/996#issuecomment-427955477 while updating. 

Does it break the whole system? It seems like the tests should fail in that case.
Or does it only affect jobs that define new classes inside the job code?

It sounds like there could be compatibility issues with jobs from the previous version too?

**Comment by carlallen** [comment]
IFF you are using psych everything is fine, if you are using syck, class serialization falls apart.

**Comment by nruth** [comment]
Thanks @carlallen for helping me with this. I think I understand what's going on now. Here are some notes in case anyone else lands here confused like I was (e.g. updating rubocop on ruby 2.4.3 when using an old dj version). 

- [syck](https://github.com/ruby/syck) is an old stdlib yaml parser, removed some time ago and replaced by psych.
- [psych](https://github.com/ruby/psych) supported some of syck's old method signatures for backwards-compatibility, but [recently removed them](https://docs.ruby-lang.org/en/2.5.0/NEWS.html), causing some old software versions (e.g. [dj](https://github.com/collectiveidea/delayed_job_active_record/issues/150)) to fail (fixed by updating dj)
- this issue is specific to special configurations (e.g. Gemfiles) using syck, which most people won't be doing. Most people also wouldn't be using it before the updates, unless using a very old version of ruby.

So I think this issue doesn't affect default installs.
Apologies for the distraction from this issue.

**Comment by carlallen** [comment]
Yeah, the only way you can expect to see this issue is if you are explicitly using syck. This is only common if your project is particularly old and there was some limitation that prevented a migration to psych. Even if you upgrade to a newer version of ruby, continuing to use sych as your yaml parser will be breaking.

**Comment by albus522** [comment]
Closing stale
