### ISSUE TITLE
Prevent from enqueue duplicated job

### ISSUE THREAD

**Issue by ghost** [collectiveidea/delayed_job#192]
DelayedJob should offer the possibility to check, when enquing a job, if a duplicate job (same object, same method, same arguments) is already present, and then not to enqueue it !

**Comment by synth** [comment]
For anyone who's looking, I created a gist that can do this via a Delayed Job plugin at the application level: https://gist.github.com/synth/fba7baeffd083a931184

**Comment by blairanderson** [comment]
a basic solution, query the handler and delete duplicates https://stackoverflow.com/a/70041500/1536309

**Comment by synth** [comment]
I posted on the SO, but I post my .02 here as well. I don't think that approach would scale well unless you had a unique key or signature of the job to do the `delete_all`. Otherwise, you're doing a slow query lookup against a very long string which won't play nice when you have thousands of records.
