### ISSUE TITLE
De-rails-ify DelayedJob

### ISSUE THREAD

**Issue by contentfree** [collectiveidea/delayed_job#515]
DelayedJob is very useful outside of Rails too. There's many hoops to jump through (including hand-forging use of Delayed::Command and requirements for Rails.root to exist).

It would be great if DJ became framework-agnostic.

**Comment by costa** [comment]
If I may, for now, can you please add rails as a dependency?
Like, to avoid `uninitialized constant Delayed::Command::Rails` — I'm currently patching guard-delayed and I wonder if I should open another issue for that error, or this one is enough.
Thanks.

**Comment by albus522** [comment]
There are already fixes for that in master.

**Comment by johnnyshields** [comment]
This issue can be closed.

**Comment by michaelirey** [comment]
I am using DJ in a non rails environment, and like @contentfree mentioned there are a few hoops to go through. Looks like this issue is more than 2 years old. @sferik Have any patches been submitted? Or are these the fixes @albus522 is talking about. If you need a patch let me know. I would like to contribute.

**Comment by sferik** [comment]
Delayed::Job still has some coupling with Rails but it should be relatively easy to use outside of a Rails environment (i.e. most of the coupling is wrapped in conditionals). There is a hard dependency on Active Support, which you could try to remove, but that would probably involving pasting lots of code from Active Support into DJ, which is probably not a worthwhile tradeoff.

@michaelirey Specifically, what issues are you running into using DJ outside of Rails? If you could open an issue for each of the “hoops” you’ve had to jump through, we could work on solving each of them individually.

I’m going to close this issue because I don’t think it’s productive to talk about “de-rails-ifying” Delayed::Job at such a high level.
