### ISSUE TITLE
delayed_job on production

### ISSUE THREAD

**Issue by remon** [collectiveidea/delayed_job#538]
I am using  delayed_job gem with my rails 3 app on development working great but when I tried to use it on production using capistrano it gives me these error

script/delayed_job: Permission denied

I am using your method and I followed These Railscast video

http://railscasts.com/episodes/171-delayed-job-revised

https://github.com/collectiveidea/delayed_job/wiki/Rails-3-and-Capistrano

ruby-on-rails ubuntu delayed-job vps railscasts

**Comment by jaykilleen** [comment]
> script/delayed_job probably does not have execute file permission.
> 
> ```
> chmod +x script/delayed_job
> ```

I have to run this everytime I ssh into the server (I am doing it myself because Capistrano doesn't seem to be able to start/stop despite it being part of my hooks). Is there a way to make the `chmod +x bin/delayed_job` permission set permanently for a user?? I'll keep trying to figure this out and comment back if I find a way. Cheers
