### ISSUE TITLE
DJ with pg schemas doesnt work

### ISSUE THREAD

**Issue by terraplane** [collectiveidea/delayed_job#895]
I use rails 4.2 and Apartment gem for selecting current schema. It is configured that DJ jobs are stored in the `public` schema. In this case DJ fails with `ActiveJob::DeserializationError: Error while trying to deserialize arguments: Couldn't find Project with 'id'=1`
The project's record is store in private schema and DJ worker didnt see it bc it wasnt switched to the private schema. I tried to move DJ jobs table also to private -- no errors, no success, nothing.

So my question is: is it possible to switch schemas inside DJ worker?

**Comment by albus522** [comment]
The only thing I can think of would be to create custom jobs. The jobs would need to serialize something generic like a model name and id. The job would then start by changing the schema, lookup the record needed and run the appropriate action. Then ensure that the connection gets reset to the public schema even if an error is encountered otherwise DJ would not be able to save any error information or mark the job as errored/failed.
All of this would be full custom as this is not a supported way to run DJ.
