### ISSUE TITLE
Git repository contains possibly corrupt files

### ISSUE THREAD

**Issue by ravicious** [collectiveidea/delayed_job#897]
Due to recent findings that [git doesn't look at checksums of downloaded files by default](https://groups.google.com/forum/#!msg/binary-transparency/f-BI4o8HZW0/MDmnWideAgAJ), I added these options to my `.gitconfig`:

```
[transfer]
  fsckObjects = true
[fetch]
  fsckObjects = true
[receive]
  fsckObjects = true
```

Today I tried to pull in delayed_job from GitHub in order to have the ability to use the functionality described in #782. `bundle install` failed while cloning the repo with the following error:

```
error: object a65393623169a7f3c617217ba6ae5be4d5358a1b: zeroPaddedFilemode: contains zero-padded file modes
fatal: Error in object
fatal: index-pack failed
```

I can confirm this comes from git as cloning the repo with my gitconfig also gives the same result.

To temporarily mitigate the problem, I removed these options from my config just to install delayed_job. For sure it'd be worth looking for the culprit.

I can do this later this week, but in case anybody else wants to tackle this – please feel free to do that.

**Comment by albus522** [comment]
So it would seem the only way to fix this issue is to completely rewrite history since the issue. Which we can't really do.

By what I can tell, the only issue this causes is that two commits that would otherwise be the same except for the zero padding would be considered different, as they are. Everything I am reading tells me most people don't even consider this an issue.

Git even allows you to ignore this particular warning as follows
```
[fsck]
	zeroPaddedFilemode = ignore
```
