### ISSUE TITLE
Delayed::Worker.raise_signal_exceptions are mistakenly caught in Worker#run

### ISSUE THREAD

**Issue by will89** [collectiveidea/delayed_job#951]
We have noticed that delayed job attempt counts increase when deploying to Heroku which uses SIGTERM to stop workers. We noticed this started happening in DJ 4.1.0, and it looks like it could be related to this change https://github.com/collectiveidea/delayed_job/commit/3b072027a3dd60b784a5ff446f55cc6de8da39b0#diff-70ead5838f9d70eb6391b0b682b035fd.

**Comment by albus522** [comment]
This is intentional and expected behavior. See the docs. Specifically:

You may need to raise exceptions on SIGTERM signals, Delayed::Worker.raise_signal_exceptions = :term will cause the worker to raise a SignalException causing the running job to abort and be unlocked, which makes the job available to other workers. The default for this option is false.
