### ISSUE TITLE
 The job has not been done. Nothing printout even though I put a print in the block no request has been made. 

### ISSUE THREAD

**Issue by bobzhang199102** [collectiveidea/delayed_job#972]
The delayed_job add jobs in the database and remove it without errors. But The job has not been done. Nothing print out even though I put a print in the block no request has been made.

**Comment by miguelgraz** [comment]
I have a similar situation, still trying to understand why it intermittently seems to add and remove some jobs to the database.

I got as far as making sure that if I have a custom job it always executes the `enqueue` method but seems to never execute neither the `perform`, `error` or `failure` one.

I had the problem with version `4.1.2`, just bumped it to `4.1.3` to test now.

**Comment by albus522** [comment]
A common cause is a rogue worker process that didn't successfully exit and is still trying to work off jobs based on old code.

Another common cause is jobs that can't be deserialized because of some failure in serialization, such as mysql cutting off text that doesn't fit in the column. This usually gets logged but has on occasion slipped through.

**Comment by miguelgraz** [comment]
Okay I believe I understood the problem I had back then and I'm gonna try to explain it here from the top of my head so bear with me if I say something silly.

- **Issue:** Job was created, added to the database and, when caught by the background worker, removed without executing or raising any exception

- **How:** The system has the following relationships:
  - A class called `Steer` that `has_many` `Question`s;
  - Both classes have subclasses and some with the same name, so `Steer::YesNo` and `Question::YesNo`;
  - The bugged code was executing a `self.delay.actual_method` from _inside_ the `Steer` class;
  - For `Steer`s with the same name of a `Question` like `YesNo` mentioned before the _issue_ explained above was seen, if there was no `Question` subclass with the same name it worked fine;

- **To Fix:** The fix was just a matter of forcing the class calling the `delay` to be the superclass, so instead of `self.delay.actual_method` it became `self.becomes(Steer).delay.actual_method`

- **Why it may be a DJ bug:** DJ seemed to have behaved somewhere in between the "execute the job" and the "I don't know this class and won't execute this job" but without raising any exception. 
I believe I personally would expect it to raise some kind of "Unknown Class" exception.


I hope this comment can help someone else, please @albus522 let me know if that makes any sense to you and if it might be a possible point to improve DJ. :smile_cat:

**Comment by albus522** [comment]
If DJ can't deserialize the job it is considered and unrecoverable failure. My guess is that the referenced class is not setup in an autoload friendly way and rails fails to access the class which then bubbles up as a deserialization error and DJ throws out the job. DJ does log deserialization failures, so it is not a silent issue as long as logging is setup correctly.

**Comment by albus522** [comment]
Closing stale
